### ISSUE TITLE
Possible usage example.

### ISSUE THREAD

**Issue by zufpi** [samwindham1/algo-trader#1]
Hi,

I'm impressed with your work !
It'd be great to have an example of how to call the 'run.py' script with relevant arguments.

Thanks and good luck !
Zuf.

**Comment by samwindham** [comment]
I haven't used this project in a while! Sorry for the dead issue. I'll update the README when I get a chance!

**Comment by samwindham** [comment]
Here's how you run a backtest: 
```
python -m backtest.run BuyAndHold -t SPY -s 2010
```

The first argument is the name of the strategy and after that you can specify the arguments. Refer to the README for more info!
